config/routes.rb
Stockslist2::Application.routes.draw do
  
  get "users/index"
  get "users/show"

  devise_for :users, controllers: { registrations: "registrations"}

  devise_scope :user do
    resources :users
  end  

  get "stock_fetch/yahoo_data"
  get "stock_fetch/yahoo_short_info"
  get "stock_fetch/stock_image", defaults: {format: :json}
  get "stock_fetch/yahoo_info"
  
  get "home/index"
  root :to => 'home#index'
  resources :stocklists
  #resources :stock_fetch
  
  scope :api do
    get "/users(.:format)" => "users#index"
    get "/users/:id(.:format)" => "users#show"
    get "/stocklists(.:format)" => "stocklists#index"
    get "/stocklists/:id(.:format)" => "stocklists#show"
    post "/stocklists(.:format)" => "stocklists#create"
    put "/stocklists/:id(.:format)" => "stocklists#update"
    delete "/stocklists/:id(.:format)" => "stocklists#destroy"
  end
end

app/models/stocklist.rb
class Stocklist < ActiveRecord::Base
  #attr_accessible :industry, :ipoyear, :marketcap, :name, :sector, :symbol, :stockexchange
  validates :symbol, :presence => true, :uniqueness => true
  #scope :for_year, lambda {|year| where("ipoyear >= ? and ipoyear <= ?", "#{year}-01-01", "#{year}-12-31")}
  
  def to_param
    "#{id} #{symbol}".parameterize
  end
end

app/controllers/stocklists_controller.rb
class StocklistsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_stocklist, only: [:show, :edit, :update, :destroy]
  layout "home"
  # GET /stocklists
  # GET /stocklists.json
  def index
    @stocklists = Stocklist.all

    respond_to do |format|
      format.html { render "angular_index" }
      format.json { render json: @stocklists }
    end
  end

  # GET /stocklists/1
  # GET /stocklists/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stocklist }
    end
  end

  # GET /stocklists/new
  # GET /stocklists/new.json
  def new
    @stocklist = Stocklist.new

    # respond_to do |format|
      # format.html # new.html.erb
      # format.json { render json: @stocklist }
    # end
  end

  # GET /stocklists/1/edit
  def edit
  end

  # POST /stocklists
  # POST /stocklists.json
  def create
    @stocklist = Stocklist.new(stocklist_params)
    #@stocklist = Stocklist.new(params[:stocklist])
    #@stocklist = Stocklist.create(stocklist_params)
    @stocklist[:ipoyear] = "#{params[:stocklist][:ipoyear]}-01-01"

    respond_to do |format|
      if @stocklist.save
        format.html { redirect_to @stocklist, notice: 'Stocklist was successfully created.' }
        format.json { render json: @stocklist, status: :created, location: @stocklist }
      else
        format.html { render :new }
        format.json { render json: @stocklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stocklists/1
  # PUT /stocklists/1.json
  def update
    params[:stocklist][:ipoyear] += "-01-01" unless params[:stocklist][:ipoyear].nil?

    respond_to do |format|
      if @stocklist.update(stocklist_params)
        format.html { redirect_to @stocklist, notice: 'Stocklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @stocklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocklists/1
  # DELETE /stocklists/1.json
  def destroy
    @stocklist.destroy

    respond_to do |format|
      format.html { redirect_to stocklists_url }
      format.json { head :no_content }
    end
  end
  
  private
  def set_stocklist
      @stocklist = Stocklist.find(params[:id])
  end
  
  def stocklist_params
    params.require(:stocklist).permit(:industry, :ipoyear, :marketcap, :name, :sector, :symbol, :stockexchange)
  end  
end

app/helpers/stocklists_helper.rb
module StocklistsHelper
  def show_ipoyear(datestr)
    datestr.nil? ? nil : Date.parse(datestr.to_s).year
  end
  
  def fetch_url(url)
    r = Net::HTTP.get_response( URI.parse( url ) )
    if r.is_a? Net::HTTPSuccess
      r.body
    else
      '<p> No data fetched</p>'
    end
  end
  
  def listed_exchanges 
    ['NYSE', 'NASDAQ', 'AMEX']
  end

end

app/views/stocklists/_angular_show_edit.html.haml
%div{"id"=>"stocklist-view-container", 
     "ng-show"=>"selectedStocklist"}
  %h4 {{selectedStocklist.symbol}}

  - if admin?
    %i{:class=>"icon-edit"}     
  %div{"contentEditable"=>"#{editable}", 
       "ng-model"=>"selectedStocklist.name"}
    {{selectedStocklist.name}}
  %br
  
  %div.inline Exchange:
  - if admin?
    %i{:class=>"icon-edit"}  
  %div.inline{"contentEditable"=>"#{editable}", 
       "ng-model"=>"selectedStocklist.stockexchange"}
    {{selectedStocklist.stockexchange}}
  %br
  
  %div.inline Industry: 
  - if admin?
    %i{:class=>"icon-edit"}
  %div.inline{"contentEditable"=>"#{editable}", 
              "ng-model"=>"selectedStocklist.industry"}
    {{selectedStocklist.industry}}
  %br  
  
  %div.inline Sector: 
  - if admin?
    %i{:class=>"icon-edit"} 
  %div.inline{"contentEditable"=>"#{editable}", 
              "ng-model"=>"selectedStocklist.sector"}
    {{selectedStocklist.sector}}
  %br
  
  %div.inline IPO Year: 
  - if admin?
    %i{:class=>"icon-edit"} 
  %div.inline{"contentEditable"=>"#{editable}", "ng-model"=>"selectedStocklist.ipoyear"}
    {{selectedStocklist.ipoyear||'NONE'}}
  %br
  
  %br
    - if admin?
      %button.button-mini{"ng-click" => "updateStocklist(selectedStocklist)", :class => 'btn'}
        Update
      %button.button-mini{"confirmed-click" => "deleteStocklist(selectedStocklist)", 
                "ng-confirm-click" => "Do you want to delete?",
                :class => 'btn btn-danger btn-primary'}
        Delete

app/views/stocklists/_form.html.haml
.clearfix
  = f.label :symbol, t("activerecord.attributes.stocklist.symbol", :default => "Symbol"), :class => :label
  .input
    = f.text_field :symbol, :class => 'text_field'
.clearfix
  = f.label :name, t("activerecord.attributes.stocklist.name", :default => "Name"), :class => :label
  .input
    = f.text_field :name, :class => 'text_field'
.clearfix
  = f.label :ipoyear, t("activerecord.attributes.stocklist.ipoyear", :default => "Ipoyear"), :class => :label
  .input
    = select_year show_ipoyear(@stocklist.ipoyear), :start_year => 1976, :end_year => Date.today.year, :field_name => :ipoyear, :prefix => :stocklist, :include_blank => true, :default => nil
.clearfix
  = f.label :stockexchange, t("activerecord.attributes.stocklist.stockexchange", :default => "Stock Exchange"), :class => :label
  .input
    = f.select :stockexchange, options = listed_exchanges, :include_blank => true, :default => nil
.clearfix
  = f.label :sector, t("activerecord.attributes.stocklist.sector", :default => "Sector"), :class => :label
  .input
    = f.text_field :sector, :class => 'text_field'
.clearfix
  = f.label :industry, t("activerecord.attributes.stocklist.industry", :default => "Industry"), :class => :label
  .input
    = f.text_field :industry, :class => 'text_field'
.clearfix
  = f.label :marketcap, t("activerecord.attributes.stocklist.marketcap", :default => "Marketcap"), :class => :label
  .input
    = f.text_field :marketcap, :class => 'text_field'

.form-actions
  %button{:class => "btn btn-primary btn-medium", :type => "submit"} Save
  = link_to "Cancel", stocklists_path, :class => 'btn btn-medium'

app/views/stocklists/_hash_info.html.haml
%table.table-bordered.table-striped.table-nonfluid{'width'=>'600px'}
  %tbody
  - #debugger
  - @inhash.first[1].each do |key, val|
    - next if key == 'symbol'
    %tr
      %td{'width'=>'200px', 'align'=>'right'}=t("stockcodes.#{key}", :default => key)
      %td{'width'=>'150px'}= val
    

app/views/stocklists/_new.html.haml
%div{"id"=>"stocklist-new-container"}
  %form{"ng-submit" => "addNewStocklist(newStocklist); newStocklist={}"}
    %p
      %input.input-small{:type => "text", "ng-model" => "newStocklist.symbol",
               :placeholder => "Symbol", :class => 'symbol_field'}
    %p
      %input.input-xlarge{:type => "text", "ng-model" => "newStocklist.name", 
                          :placeholder => "Name"}
    %p
      %input.input-medium{:type => "text", "ng-model" => "newStocklist.stockexchange",
                          :placeholder => "Exchange"}
    %p
      %input.input-medium{:type => "text", "ng-model" => "newStocklist.industry", 
                          :placeholder => "Industry"}
    %p
      %input.input-medium{:type => "text", "ng-model" => "newStocklist.sector", 
                          :placeholder => "Sector"}
    %p  
      %input.input-mini{:type => "text", "ng-model" => "newStocklist.ipoyear", 
                        :placeholder => "IPO-Year"}
    %p  
      %button.button-medium{:type => "Submit"}
        Save

app/views/stocklists/_short_info.html.haml
%div#stock_short_info
  %div
    %img#stock_image_short{src: "", data: {fancydiv: "#fancydiv"}}
    %div#fancydiv
      %img#fancy_image{src: ""}
      %table.table.table-bordered.table-condensed#period_selection
        %tr
          %td{style: "color:blue; text-decoration:underline;"} 1d
          %td 3d
          %td 5d
          %td 1M
          %td 3M
          %td 6M
          %td 1Y
          %td 2Y
          %td 5Y
          %td max
      %script{:"data-turbolinks-track"=>"true", :src=>"/assets/home.js?body=1"}

  %table.table-bordered.table-striped
    %tbody
      %tr
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.name", :default => 'name')
        %td#name{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.stockExchange", :default => 'stockExchange')
        %td#stockExchange{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.lastTrade", :default => 'lastTrade')
        %td#lastTrade{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.change", :default => 'change')
        %td#change{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.dayRange", :default => 'dayRange')
        %td#dayRange{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.changeInPercent", :default => 'changeInPercent')
        %td#changeInPercent{'width'=>'160px'}  
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.weeks52Range", :default => 'weeks52Range')
        %td#weeks52Range{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.marketCap", :default => 'marketCap')
        %td#marketCap{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.movingAve50days", :default => 'movingAve50days')
        %td#movingAve50days{'width'=>'160px'}
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.movingAve200days", :default => 'movingAve200days')
        %td#movingAve200days{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.earningsPerShare", :default => 'earningsPerShare')
        %td#earningsPerShare{'width'=>'160px'}       
        %td{'width'=>'160px', 'align'=>'right'}
        %td{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.peRatio", :default => 'peRatio')
        %td#peRatio{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.pegRatio", :default => 'pegRatio')
        %td#pegRatio{'width'=>'160px'}
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.bookValue", :default => 'bookValue')
        %td#bookValue{'width'=>'160px'} 
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.pricePerBook", :default => 'pricePerBook')
        %td#pricePerBook{'width'=>'160px'}                
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.pricePerSales", :default => 'pricePerSales')
        %td#pricePerSales{'width'=>'160px'}
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.ebitda", :default => 'ebitda')
        %td#ebitda{'width'=>'160px'} 
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.dividendPerShare", :default => 'dividendPerShare')
        %td#dividendPerShare{'width'=>'160px'}
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.dividendYield", :default => 'dividendYield')
        %td#dividendYield{'width'=>'160px'}               
      %tr        
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.exDividendDate", :default => 'exDividendDate')
        %td#exDividendDate{'width'=>'160px'}
        %td{'width'=>'160px', 'align'=>'right'}=t("stockcodes.dividendPayDate", :default => 'dividendPayDate')
        %td#dividendPayDate{'width'=>'160px'}

:coffee
  $().ready ->
    $('#stock_image_short').fancyZoom({scaleImg: true, closeOnClick: false, width: 380, height: 200})

app/views/stocklists/_stockinfo.html.haml
- symbol = @stocklist.symbol
.span7.pull-left
  .span3.pull-left
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::BASICHASH)
  
  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::RATIOHASH)

  .span3.pull-left  
    %img{:src => StockGoogleGraph.get_google_graph_url(symbol)}

  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::DIVIDENDHASH)

  .span3.pull-left  
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::PRICEHASH)

  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::WEEKS52)

  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::MOVINGAVE)

  .span3.pull-left
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::MARKETOPENHASH)

  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash = StockDataFetch.specialized_quotes(symbol, YahooFinance::VOLUMEHASH)

  .span3.pull-right
    = render :partial => 'hash_info', :object => @inhash =  StockDataFetch.specialized_quotes(symbol, YahooFinance::DATEHASH)

-#  %iframe{:height => "430", :src => "http://www.yahoo.com", :title => "Google Stock Info", :width => "450"}
-#    %p Incomplete page rendering

app/views/stocklists/angular_index.html.haml
- editable = admin? ? true : false
  
%div{"ng-app" => "Stocklists", "ng-controller" => "StocklistsCtrl"}
  - if admin?
    %button.button-mini{"ng-click" => "showNewStocklist()", :class => 'btn btn-primary pull-right'}
      Add
  %div{style: "width: 380px"}
    %h4{style: "color: blue; display: inline-block"} Listed Stocks
    %input{type:"text", "ng-model" => 'search.symbol', placeholder: "Symbol",
          class: "inline input-mini search-query pull-right symbol_field"}
    %input{type:"text", "ng-model" => 'search.name', placeholder: "Name",
          class: "inline input-small search-query pull-right"}    

  %div{"id" => "stocklist-list-container"}
    %ul
      %li{"ng-repeat"=>"stocklist in stocklists| filter:search | orderBy:predicate:reverse", 
          "ng-click"=>"showStocklist(stocklist)"}
        %h5 {{stocklist.symbol}} 
        %small{:display => 'inline-block'} {{stocklist.name}}
        - if admin?
          %p{"confirmed-click" => "deleteStocklist(stocklist)", 
                  "ng-confirm-click" => "Do you want to delete?",
                   :class => 'icon-remove pull-right angular_remove'}

  %div{"id"=>"stocklist-view-container", 
       "ng-show"=>"selectedStocklist"}
    %h4 {{selectedStocklist.symbol}}

    - if admin?
      %i{:class=>"icon-edit"}     
    %div{"contentEditable"=>"#{editable}", 
         "ng-model"=>"selectedStocklist.name"}
      {{selectedStocklist.name}}
    %br
    
    %div.inline Exchange:
    - if admin?
      %i{:class=>"icon-edit"}  
    %div.inline{"contentEditable"=>"#{editable}", 
         "ng-model"=>"selectedStocklist.stockexchange"}
      {{selectedStocklist.stockexchange}}
    %br
    
    %div.inline Industry: 
    - if admin?
      %i{:class=>"icon-edit"}
    %div.inline{"contentEditable"=>"#{editable}", 
                "ng-model"=>"selectedStocklist.industry"}
      {{selectedStocklist.industry}}
    %br  
    
    %div.inline Sector: 
    - if admin?
      %i{:class=>"icon-edit"} 
    %div.inline{"contentEditable"=>"#{editable}", 
                "ng-model"=>"selectedStocklist.sector"}
      {{selectedStocklist.sector}}
    %br
    
    %div.inline IPO Year: 
    - if admin?
      %i{:class=>"icon-edit"} 
    %div.inline{"contentEditable"=>"#{editable}", "ng-model"=>"selectedStocklist.ipoyear"}
      {{selectedStocklist.ipoyear||'NONE'}}
    %br
    
    %br
      - if admin?
        %button.button-mini{"ng-click" => "updateStocklist(selectedStocklist)", :class => 'btn'}
          Update
        %button.button-mini{"confirmed-click" => "deleteStocklist(selectedStocklist)", 
                  "ng-confirm-click" => "Do you want to delete?",
                  :class => 'btn btn-danger btn-primary'}
          Delete
          
  = render :partial => "short_info"
      
  = render :partial => "new"
       
       

app/views/stocklists/edit.html.haml
- @no_sidebar = true

.span3
  = form_for @stocklist, :url => stocklist_path(@stocklist), :html => { :class => "edit_stocklist", :id => "edit_stocklist" } do |f|
    %input{:name => "_method", :type => "hidden", :value =>"put"}
    = render :partial => "form", :locals => {:f => f}

app/views/stocklists/index.html.haml
- model_class = Stocklist
.page-header
  %h4.blue Listed Stocks
  
.span5.pull-left
  %table.table.table-striped.table-hover.table-condensed
    %thead
      %tr
        %th= model_class.human_attribute_name(:symbol)
        %th= model_class.human_attribute_name(:name)
        %th= model_class.human_attribute_name(:ipoyear)
        %th= model_class.human_attribute_name(:stockexchange)
        %th= model_class.human_attribute_name(:sector)
        %th= model_class.human_attribute_name(:industry)
        %th= model_class.human_attribute_name(:marketcap)
        - if admin?
          %th=t '.actions', :default => t("helpers.actions")
    %tbody
      - @stocklists.each do |stocklist|
        %tr
          %td= link_to stocklist.symbol, stocklist_path(stocklist)
          %td= stocklist.name
          %td= stocklist.ipoyear.year if (stocklist.ipoyear)
          %td= stocklist.stockexchange
          %td= stocklist.sector
          %td= stocklist.industry
          %td= stocklist.marketcap
          -if admin?
            %td
              = link_to '', edit_stocklist_path(stocklist), {:class => 'icon-edit', :title1=>t('.edit', :default => t("helpers.links.edit"))}
              = link_to '', stocklist_path(stocklist), :method => :delete, data: { confirm: t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'icon-remove'
  
  - if admin?
    = link_to t('.new', :default => t("helpers.links.new")), new_stocklist_path, :class => 'btn btn-primary'

app/views/stocklists/new.html.haml
- @no_sidebar = true
.span3
  = form_for @stocklist, :url => stocklists_path, :html => { :class => :form } do |f|
    = render :partial => "form", :locals => {:f => f}

app/views/stocklists/show.html.haml
.span3
  %p#notice= notice
  
  %label{:class => "label"}= t("activerecord.attributes.stocklist.symbol", :default => "Symbol") + ":"
  %p= @stocklist.symbol
  %label{:class => "label"}= t("activerecord.attributes.stocklist.name", :default => "Name") + ":"
  %p= @stocklist.name
  %label{:class => "label"}= t("activerecord.attributes.stocklist.ipoyear", :default => "Ipoyear") + ":"
  %p= show_ipoyear @stocklist.ipoyear
  %label{:class => "label"}= t("activerecord.attributes.stocklist.stockexchange", :default => "Stock Exchange") + ":"
  %p= @stocklist.stockexchange
  %label{:class => "label"}= t("activerecord.attributes.stocklist.sector", :default => "Sector") + ":"
  %p= @stocklist.sector
  %label{:class => "label"}= t("activerecord.attributes.stocklist.industry", :default => "Industry") + ":"
  %p= @stocklist.industry
  %label{:class => "label"}= t("activerecord.attributes.stocklist.marketcap", :default => "Marketcap") + ":"
  %p= @stocklist.marketcap

  - if admin?  
    .form-actions 
      = link_to "Edit", edit_stocklist_path(@stocklist), :class => 'btn btn-small'
      = link_to "Delete", stocklist_path(@stocklist), :method => "delete", data: {confirm:  t('web-app-theme.confirm', default: 'Are you sure?')}, :class => 'btn btn-small btn-danger'

#stock_info
#stock_info2

:coffee
  load_yahoo_info "#{stock_fetch_yahoo_data_path}?yahoo_symbol=#{@stocklist.symbol}"